// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "@monad-ac/order-storage-preview/contracts/OrderStorageKernel.sol";
import "./DirectTakerEscrowOrderBookBase.sol";

contract DirectTakerContiguousOrderBook is DirectTakerEscrowOrderBookBase {
    using OrderStorageKernel for bytes32;
    constructor(address base_,address quote_,address surplusRecipient_,bytes32 marketId_,uint64 priceTick_,uint256 baseRawPerLot_,uint256 quoteRawPerLot_,uint96 minimumOrderLots_,uint96 minimumResidualLots_,uint8 baseDecimals_,uint8 quoteDecimals_)
        DirectTakerEscrowOrderBookBase(base_,quote_,surplusRecipient_,marketId_,priceTick_,baseRawPerLot_,quoteRawPerLot_,minimumOrderLots_,minimumResidualLots_,baseDecimals_,quoteDecimals_){marketId_.initialize();}

    function post(bytes32 suppliedMarket,uint96 lots)external nonReentrant returns(uint96 handle){_requireMarket(suppliedMarket);_validatePostLots(lots);uint256 baseRaw=_baseRaw(lots);_pullExact(baseToken,msg.sender,baseRaw);handle=marketId.post(msg.sender,priceTick,lots);lockedBaseRaw+=baseRaw;_checkEscrow();emit OrderPosted(marketId,handle,msg.sender,lots,baseRaw);}
    function cancel(bytes32 suppliedMarket,uint96 handle)external nonReentrant{_requireMarket(suppliedMarket);uint96 lots=marketId.cancel(msg.sender,handle);uint256 baseRaw=_baseRaw(lots);lockedBaseRaw-=baseRaw;_pushExact(baseToken,msg.sender,baseRaw);_checkEscrow();emit OrderCancelled(marketId,handle,msg.sender,lots,baseRaw);}
    function refresh(bytes32 suppliedMarket,uint96[] calldata cancelHandles,uint96[] calldata postLots)external nonReentrant returns(uint96[] memory newHandles){_requireMarket(suppliedMarket);uint256 postedLots;for(uint256 i;i<postLots.length;++i){_validatePostLots(postLots[i]);postedLots+=postLots[i];}uint256 escrowedBaseRaw=_baseRaw(postedLots);if(escrowedBaseRaw!=0)_pullExact(baseToken,msg.sender,escrowedBaseRaw);uint256 cancelledLots;for(uint256 i;i<cancelHandles.length;++i){uint96 lots=marketId.cancel(msg.sender,cancelHandles[i]);cancelledLots+=lots;emit OrderCancelled(marketId,cancelHandles[i],msg.sender,lots,_baseRaw(lots));}newHandles=new uint96[](postLots.length);for(uint256 i;i<postLots.length;++i){uint96 handle=marketId.post(msg.sender,priceTick,postLots[i]);newHandles[i]=handle;emit OrderPosted(marketId,handle,msg.sender,postLots[i],_baseRaw(postLots[i]));}uint256 refundedBaseRaw=_baseRaw(cancelledLots);lockedBaseRaw=lockedBaseRaw+escrowedBaseRaw-refundedBaseRaw;if(refundedBaseRaw!=0)_pushExact(baseToken,msg.sender,refundedBaseRaw);_checkEscrow();if(postedLots>type(uint96).max||cancelledLots>type(uint96).max)revert AmountOverflow(postedLots+cancelledLots,1);emit OrderRefreshed(marketId,msg.sender,uint96(cancelledLots),uint96(postedLots),refundedBaseRaw,escrowedBaseRaw);}
    function take(bytes32 suppliedMarket,uint96 maxLots,uint32 maxFills,uint256 maxQuoteRaw,uint96 minLotsReceived,uint256 deadline)external nonReentrant returns(FillReceipt[] memory receipts){_requireMarket(suppliedMarket);_validateTake(maxLots,maxFills,maxQuoteRaw,minLotsReceived,deadline);(OrderStorageKernel.Fill[] memory fills,uint96 actualLots)=marketId.consumeUpToWithFills(priceTick,maxLots,maxFills);if(actualLots<minLotsReceived)revert MinimumLots(actualLots,minLotsReceived);if(fills.length!=0&&fills[fills.length-1].remaining!=0&&fills[fills.length-1].remaining<minimumResidualLots)revert ResidualBelowMinimum(fills[fills.length-1].remaining,minimumResidualLots);uint256 actualQuoteRaw=_quoteRaw(actualLots);if(actualQuoteRaw>maxQuoteRaw)revert QuoteLimit(actualQuoteRaw,maxQuoteRaw);uint256 actualBaseRaw=_baseRaw(actualLots);uint256 quoteBefore=IDirectAsset(quoteToken).balanceOf(address(this));_pullExact(quoteToken,msg.sender,actualQuoteRaw);lockedBaseRaw-=actualBaseRaw;receipts=new FillReceipt[](fills.length);for(uint256 i;i<fills.length;++i){uint256 baseRaw=_baseRaw(fills[i].quantity);uint256 quoteRaw=_quoteRaw(fills[i].quantity);_pushExact(quoteToken,fills[i].maker,quoteRaw);receipts[i]=FillReceipt(marketId,priceTick,fills[i].handle,fills[i].maker,fills[i].quantity,baseRaw,quoteRaw,fills[i].remaining);emit TradeSettled(marketId,fills[i].handle,fills[i].maker,msg.sender,priceTick,fills[i].quantity,baseRaw,quoteRaw,fills[i].remaining);}_pushExact(baseToken,msg.sender,actualBaseRaw);uint256 quoteAfter=IDirectAsset(quoteToken).balanceOf(address(this));if(quoteAfter!=quoteBefore)revert TokenDeltaMismatch(quoteToken,address(this),quoteBefore,quoteAfter);_checkEscrow();}
    function order(bytes32 suppliedMarket,uint96 handle)external view returns(OrderStorageKernel.Order memory){_requireMarket(suppliedMarket);return marketId.order(handle);}
    function level(bytes32 suppliedMarket)external view returns(uint96 head,uint96 tail){_requireMarket(suppliedMarket);return marketId.level(priceTick);}
}
